# Estágio de Build
FROM node:26-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG PUBLIC_STRIPE_KEY
ARG SECRET_STRIPE_KEY
ARG PUBLIC_FRONTEND_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG DB_CONN_STR
ARG MAIL_HOST
ARG MAIL_USER
ARG MAIL_PASS
ARG MAIL_PORT
ARG PUBLIC_FREE_TRIAL_PRICE_ID
ARG PUBLIC_STANDARD_PRICE_ID
ARG PUBLIC_ADVANCED_PRICE_ID
ARG PUBLIC_PRO_PRICE_ID
ARG FREE_TRIAL_PRICE_ID
ARG STANDARD_PRICE_ID
ARG ADVANCED_PRICE_ID
ARG PRO_PRICE_ID

RUN npm run build
RUN npm prune --production

# Estágio Final (Runtime)
FROM node:26-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production

ARG PUBLIC_STRIPE_KEY
ARG SECRET_STRIPE_KEY
ARG PUBLIC_FRONTEND_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG DB_CONN_STR
ARG MAIL_HOST
ARG MAIL_USER
ARG MAIL_PASS
ARG MAIL_PORT
ARG PUBLIC_FREE_TRIAL_PRICE_ID
ARG PUBLIC_STANDARD_PRICE_ID
ARG PUBLIC_ADVANCED_PRICE_ID
ARG PUBLIC_PRO_PRICE_ID
ARG FREE_TRIAL_PRICE_ID
ARG STANDARD_PRICE_ID
ARG ADVANCED_PRICE_ID
ARG PRO_PRICE_ID

CMD [ "node", "build" ]